name: CI

on: [push]

jobs:
  build-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run script
      run: ci/build.sh
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: install
        path: install
